version: '2'

services:
  syncthing:
    image: cmehay/syncthing
    restart: always
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - "config:/home/syncthing/.config/syncthing"
      - "data:/home/syncthing/Sync"
    environment:
        ENTRYPOINT_USER: '1000' # optional. 1000 by default
        ENTRY: '1000' # optional. 1000 by default

volumes:
  config:
    driver: local
  data:
    driver: local
